import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Registra as fontes disponibilizadas pelo Next.js para uso global no CSS.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // Metadados padrão compartilhados pelas páginas do sistema.
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout raiz compartilhado por todas as rotas da aplicação.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className= "h-full"
    >
      <body>{children}</body>
    </html>
  );
}
